{% set git_rev = "4afd47b520977ca0a00bdfe903be57013f53080c" %}
# increase this by 1 everytime you change the git commit above without also
# changing the `version`
{% set git_rev_count = "0" %}

{% set name = "gromacs-metatomic" %}
{% set conda_version = "2026.0" %}

# Use a higher build number for prefered variants, to ensure that they are
# picked first by conda's solver, and installed where the platform supports it.
{% set build = 0 %}
{% set build = build + 100 %}  # [mpi == 'nompi' and double == 'no' and cuda_compiler_version == "None"]

package:
  name: {{ name|lower }}
  version: {{ conda_version }}.mta{{ git_rev_count }}

source:
  git_url: https://github.com/metatensor/gromacs.git
  git_rev: {{ git_rev }}
  depth: 1

build:
  number: {{ build }}
  string: >-
    nompi_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [mpi == 'nompi' and double == 'no' and cuda_compiler_version == "None"]
    mpi_{{ mpi }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [mpi != 'nompi' and double == 'no' and cuda_compiler_version == "None"]
    mpi_{{ mpi }}_cuda_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [mpi != 'nompi' and double == 'no' and cuda_compiler_version != "None"]
    nompi_dblprec_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [mpi == 'nompi' and double == 'yes' and cuda_compiler_version == "None"]
    mpi_{{ mpi }}_dblprec_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [mpi != 'nompi' and double == 'yes' and cuda_compiler_version == "None"]
    nompi_cuda_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [mpi == 'nompi' and double == 'no' and cuda_compiler_version != "None"]
  skip: true  # [win]
  skip: true  # [mpi == "openmpi" and arm64]
  skip: true  # [double == "yes" and cuda_compiler_version != "None"]

  # fails with: /usr/local/cuda/lib64/libcudart_static.a: error adding symbols: file in wrong format
  skip: true  # [(aarch64 or ppc64le) and double == "no" and cuda_compiler_version != "None"]

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - {{ stdlib("c") }}
    - cmake >=3.28
    - pocl
    - perl
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - coreutils  # [cuda_compiler_version != "None"]
    - cuda-toolkit  # [cuda_compiler_version != "None"]
  host:
    - python
    - ocl-icd  # [linux and cuda_compiler_version == "None"]
    - cuda-toolkit  # [cuda_compiler_version != "None"]
    - khronos-opencl-icd-loader  # [osx]
    - libhwloc 2.*
    - fftw
    - {{ mpi }}  # [mpi != 'nompi']
    - libmetatomic-torch >=0.1.5,<0.2.0
    # always build against the CPU version of libtorch, we can still pick the
    # cuda one at runtime
    - libtorch * cpu*
    - libtorch
  run:
    - python
    - ocl-icd  # [linux and cuda_compiler_version == "None"]
    - cuda-toolkit  # [cuda_compiler_version != "None"]
    - khronos-opencl-icd-loader  # [osx]
    - ocl_icd_wrapper_apple  # [osx]
    - fftw
    - libhwloc 2.*
    - {{ mpi }}  # [mpi != 'nompi']
    - __cuda  # [not osx and cuda_compiler_version != "None"]
    - libmetatomic-torch >=0.1.7,<0.2.0
    - libmetatensor-torch >=0.8.2,<0.9.0
    - libmetatensor >=0.1.19,<0.2.0

test:
  commands:
    - gmx -version  # [mpi == 'nompi' and double == 'no']
    - gmx_d -version  # [mpi == 'nompi' and double == 'yes']
    - export OMPI_MCA_plm=isolated  # [mpi == "openmpi" and linux]
    - export OMPI_MCA_btl_vader_single_copy_mechanism=none  # [mpi == "openmpi" and linux]
    - export OMPI_MCA_rmaps_base_oversubscribe=yes  # [mpi == "openmpi" and linux]
    - gmx_mpi -version  # [mpi != 'nompi' and double == 'no']
    - gmx_mpi_d -version  # [mpi != 'nompi' and double == 'yes']:

about:
  home: https://docs.metatensor.org/metatomic/latest/engines/gromacs.html
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'Metatomic-enabled version of GROMACS'
  description: Metatomic-enabled version of GROMACS
  doc_url: https://docs.metatensor.org/metatomic/latest/engines/gromacs.html
  dev_url: https://github.com/metatensor/gromacs

extra:
  recipe-maintainers:
    - HaoZeke
    - Luthaf
    - PicoCentauri
